KofteBlog/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .md_view import markdown_uploader
from .sitemap import StaticViewSitemap, PostSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'post': PostSitemap,
}

urlpatterns = [
    path('podcast/', include('podcast.urls')),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
    path('panel/', include('panel.urls')),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('feed/', views.SiteFeed(), name="feed"),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name="detail"),
    path('tag/', views.TagListView.as_view(), name="tag"),
    path('<slug:slug>/', views.PageView.as_view(), name="page"),
]

blog/forms.py
from django import forms
from .models import Comment
from django.utils.translation import gettext as _


class UserCommentForm(forms.ModelForm):
    fullname = forms.CharField()
    question = forms.IntegerField(widget=forms.widgets.HiddenInput())
    answer = forms.CharField()

    class Meta:
        model = Comment
        fields = ['parent', 'comment', 'answer']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].widget = forms.widgets.HiddenInput()
        self.fields['fullname'].required = False
        self.fields['comment'].widget.attrs.update({
            'placeholder': _('Put your comment here'),
            'class': 'textfield',
            'required': True,
        })
        self.fields['answer'].widget.attrs.update({
            'placeholder': _('Answer for the question above'),
            'required': True,
        })

    def is_valid(self):
        valid = super().is_valid()
        if not valid:
            return False
        if self.cleaned_data['fullname']:
            return False
        return True


class CommentForm(UserCommentForm):
    class Meta:
        model = Comment
        fields = ['parent', 'user_name', 'user_email', 'comment']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update({
            'placeholder': _("User's name"), 'class': 'singleline', 'required': True
        })
        self.fields['user_email'].widget.attrs.update({
            'placeholder': _("User's email address"), 'class': 'singleline', 'required': True
        })

templates/partials/comment.html
{% load markdown_tags %}
{% load i18n %}

<div id="comment_{{ comment.id }}" class="comment{% if comment.parent %} comment_child{% endif %}">
    <div class="comment_header">
        <img class="comment_avatar" src="{{ comment.get_avatar }}">
        <span class="username">
            {{ comment.user_name }}
            {% if comment.user.is_superuser %} - Admin{% endif %} - 
            <a href="{{ post.get_absolute_url }}#comment_{{ comment.id }}">
                <i class="fas fa-link"></i>
            </a>
        </span>
        <span class="right">
            {{ comment.sub_time|date:"d/m/y - G:i" }}
            <a href="javascript:;" onclick="buttonClick({% if comment.parent %}{{ comment.parent.id }}{% else %}{{ comment.id }}{% endif %});">
                {% trans "Reply" %}
            </a>
        </span>
        </div>
    <div class="comment_body">
        {{ comment.comment|escape|render_md }}
    </div>
</div>

templates/partials/comment_form.html
{% load i18n %}

<style>.fly{height:0;visibility:hidden;}</style>

<div id="comment_form" class="comment_form">
    {% if post.comments.count != 0 %}
        <h3>{% trans "Leave a Comment" %}</h3>
    {% endif %}
    {% if com_err %}<p id="err">{{ com_err }}</p>{% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.parent }}
        <input name="question" id="id_question" type="hidden" value="{{ question.pk }}">
        {% if form.user_name %}
            <p>{{ form.user_name }}</p>
            <p>{{ form.user_email }}</p>
        {% endif %}
        <p>
            {{ form.comment }}
            <small class="right md-sheet">
                {% trans "You can use Markdown to give style to your comment" %}<br>
                <a href="https://www.markdownguide.org/cheat-sheet" target="_Blank">
                    {% trans "Markdown Cheatsheat" %}
                </a>
            </small>
            <br>
        </p>
        <p class="comment_question">
            <small>{% trans 'To write a comment please answer the question' %}</small><br>
            <b>{% trans 'Question' %}:</b> <u>{{ question.question }}</u>
        </p>
        {{ form.answer }}
        <div class="fly">
            <p>{% trans 'Please do not fill this fields if you think you are a human or any other sentient being. This is just a trap for bots.' %}</p>
            <p>{{ form.fullname }}</p>
        </div>
        <input id="comment_submit" type="submit" value="{% trans "Submit Comment" %}" />
    </form>
</div>

templates/partials/feed.html
{% load markdown_tags %}
{% load i18n %}

{{ obj.pub_time }}
{{ obj.desc|render_md }}
<a href="http://{{ request.META.HTTP_HOST }}{{ obj.get_absolute_url }}" target="_Blank">{% trans "Read More" %}</a>
<hr>

templates/partials/post_header.html
{% load i18n %}

<div class="post_header">
    {% if request.get_full_path == "/" %}
        <h1 id="{{ post.url }}">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h1>
    {% else %}
        <h1>{{ post.title }}</h1>
    {% endif %}
    {% if post.pub_time %}
        <p class="date">{{ post.pub_time|date }}
            <span class="right">
                <a href="{{ post.get_absolute_url }}#comments">
                    {% blocktrans count count=post.comments.count %}{{ count }} Comment{% plural %}{{ count }} Comments{% endblocktrans %}
                </a>
        </span>
        </p>
        <p>
            {% for tag in post.get_tag_list %}
                {% if forloop.first %}
                {% else %} 
                {% endif %}
                    <a href="{% url 'blog:tag' %}?q={{ tag }}">
                        #{{ tag }}
                    </a> 
            {% endfor %}
        </p>
    {% endif %}
</div>

templates/partials/thumbnail.html
{% load thumbnail %}

{% thumbnail post.thumb "600x360" quality=75 as im %}
    <a href="{{ url }}" {% if nt %}target="_Blank"{% endif %}>
        <img class="thumbnail" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ post.title }}">
    </a>
{% endthumbnail %}