KofteBlog/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .md_view import markdown_uploader
from .sitemap import StaticViewSitemap, PostSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'post': PostSitemap,
}

urlpatterns = [
    path('podcast/', include('podcast.urls')),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
    path('panel/', include('panel.urls')),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('feed/', views.SiteFeed(), name="feed"),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name="detail"),
    path('tag/', views.TagListView.as_view(), name="tag"),
    path('<slug:slug>/', views.PageView.as_view(), name="page"),
]

blog/models.py
import re

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext as _

from martor.models import MartorField

from .utils import slug_generator, get_gravatar


class ContentAbstractModel(models.Model):
    """
    Abstract class for contents. It contains must have fields and functions for a content.
    """
    title = models.CharField(_("Title"), max_length=200)
    url = models.SlugField(_("Url"), max_length=200, blank=True)
    desc = models.TextField(_("Description"), max_length=1000, null=True)
    keywords = models.CharField(_("Keywords"), max_length=1000, null=True, blank=True)
    body = MartorField(_("Body"))
    thumb = models.ImageField(_("Thumbnail"), upload_to="thumbs/%Y/%m", null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def get_tag_list(self):
        """
        A basic regular expression for converting keywords field to a list.
        """
        if self.keywords:
            return re.split(', ?', self.keywords)

    def save(self, *args, **kwargs):
        # Checks if there is a slug, if not calls slug_generator.
        if not self.url:
            self.url = slug_generator(self)
        super(ContentAbstractModel, self).save(*args, **kwargs)


class Page(ContentAbstractModel):
    order = models.PositiveSmallIntegerField(_("Order"), unique=True)

    class Meta:
        verbose_name = _("Page")
        verbose_name_plural = _("Pages")
        ordering = ['order']

    def get_absolute_url(self):
        return reverse('blog:page', args=[str(self.url)])


class Post(ContentAbstractModel):
    pub_time = models.DateTimeField(_("Publish Time"), null=True, blank=True)
    draft = models.BooleanField(_("Draft"), default=True)
    hit_count = models.PositiveIntegerField(_("Hit Count"), default=0)

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ['-pub_time']

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.url)])

    def add_hit(self):
        """ The most ugly, yet still functional hit counter """
        self.hit_count += 1
        self.save()

    def save(self, *args, **kwargs):
        # Checks if post is draft and has publish time info. If both are not, fills with current time.
        if not self.draft and not self.pub_time:
            self.pub_time = timezone.now()
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", verbose_name=_("Post"), on_delete=models.CASCADE)
    parent = models.ForeignKey("self", related_name="child", verbose_name=_("Parent"),
                               on_delete=models.SET_NULL, blank=True, null=True,
                               limit_choices_to={'parent': None})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('User'),
                             blank=True, null=True, related_name="comments",
                             on_delete=models.SET_NULL)
    user_name = models.CharField(_("User's name"), max_length=50, null=True, blank=True)
    user_email = models.EmailField(_("User's email address"), null=True, blank=True)
    sub_time = models.DateTimeField(_('Submit Time'), default=None, db_index=True, blank=True)
    comment = models.TextField(_("Comment"))

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['sub_time']

    def __str__(self):
        return "%s: %s..." % (self.user_name, self.comment[:50])

    def get_avatar(self):
        return get_gravatar(self.user_email)

    def save(self, *args, **kwargs):
        if self.sub_time is None:
            self.sub_time = timezone.now()
        if self.user:
            self.user_name = self.user.get_full_name()
            self.user_email = self.user.email
        else:
            if self.user_name is None:
                self.user_name = _("Anonymous")
        super(Comment, self).save(*args, **kwargs)


class Question(models.Model):
    question = models.CharField(_("Question"), max_length=200)
    answers = models.TextField(_("Answers"), help_text=_("For seperate answers, please use new lines."))

    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")

    def __str__(self):
        return self.question

    def check_answer(self, **kwargs):
        """
        A simple function to create a list from object's answers and checks if given one is in it.
        To use it, call it as **object**.check_answer(answer=**keyword**)
        """
        if kwargs['answer'] in self.answers.splitlines():
            return True


class GivenAnswer(models.Model):
    question = models.ForeignKey(Question, verbose_name=_("Question"), on_delete=models.CASCADE)
    answer = models.CharField(_("Answer"), max_length=200)
    count = models.PositiveSmallIntegerField(_("Count"), default=0)
    correct = models.BooleanField(_("Correct"), default=False)

    class Meta:
        verbose_name = _("Given Answer")
        verbose_name_plural = _("Given Answers")

    def __str__(self):
        return "%s - %s" % (self.answer, self.question.__str__())

    def save(self, *args, **kwargs):
        # Adds one to objects count everytime it got updated.
        self.count = self.count + 1
        super(GivenAnswer, self).save(*args, **kwargs)

templates/base.html
{% load static %}
{% load i18n %}
{% load pages %}

{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <title>{% block title %}{{ block.super }}Köfteistan{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
        <link rel="alternate" type="application/rss+xml" title="RSS" href="/feed/">
        <link href="{% static "favicon.ico" %}" rel="icon">
        <meta property="og:locale" content="{{ LANGUAGE_CODE }}">
        <meta property="og:type" content="{% if request.get_full_path == "/" %}website{% else %}article{% endif %}" />
        <meta property="og:title" content="{% block og_title %}{{ block.super }}Köfteistan{% endblock og_title %}">
        <meta name="description" content="{% block desc %}Köfteist Köfte'nin Kafasından Geçenler{% endblock desc %}">
        <meta name="keywords" content="{% block keywords %}Köfteist Köfte, Blog{{ block.super }}{% endblock keywords %}">
        <meta property="og:url" content="{% block og_url %}http://{{ request.META.HTTP_HOST }}{{ block.super }}{% endblock og_url %}">

        {% block extra_seo %}
        {{ block.super }}
        {% endblock extra_seo %}
    </head>

    <body>
        <header>
            <h1><a href="/">Köfteistan</a></h1>
            <h2>Köfteist Köfte'nin Kafasından Geçenler</h2>
            <nav>
                {% list_pages as pages %}
                {% for page in pages %}
                    <a href="{{ page.get_absolute_url }}">{{ page.title }}</a> /
                {% endfor %}
                <a href="#footer">{% trans "Links" %}</a>
            </nav>

            {% block extra_header %}
            {% endblock extra_header %}

        </header>

        {% block body %}
        {% endblock body %}

        <footer id="footer">
            <nav>
                <a href="https://gitlab.com/kofteistkofte/"><i class="fab fa-gitlab"></i> Gitlab</a> /
                <a rel="me" href="https://mastodon.technology/@kofteistkofte"><i class="fab fa-mastodon"></i> Mastodon</a> /
                <a href="https://www.youtube.com/user/kofteistkofte/"><i class="fab fa-youtube"></i> Youtube</a> /
                <a href="mailto://kofteistkofte@gmail.com"><i class="fa fa-at"></i> Mail</a> /
                <a href="/feed/"><i class="fa fa-rss"></i> RSS</a> /
                <a href="/podcast/kernelle-sohbet"><i class="fa fa-podcast"></i> Kernelle Sohbet</a>
            </nav>
            <p>
                Köfteist Köfte'nin kafasından geçenlerle dolu nacizhane blog.
                </br><br>
                {% blocktrans with gitlab='<a href="https://gitlab.com/kofteistkofte/kofteistan.com">Gitlab</a>' %}You can see the codes of this website at {{ gitlab }}.{% endblocktrans %}<br>
                {% blocktrans with icon='<i class="fa fa-heart"></i>' %}Feel FREE to fork it. {{ icon }}{% endblocktrans %}
            </p>
        </footer>

        {% block js %}
        {{ block.super }}
        {% endblock js %}        
    </body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% load static %}
{% load markdown_tags %}
{% load i18n %}

{% block title %}
{{ post.title }} | {{ block.super }}
{% endblock title %}

{% block og_title %}{{ post.title }} | {{ block.super }}{% endblock og_title %}
{% block desc %}{{ post.desc }}{% endblock desc %}
{% block keywords %}{{ block.super }}, {{ post.keywords }}{% endblock keywords %}
{% block og_url %}{{ block.super }}{{ post.get_absolute_url }}{% endblock og_url %}

{% block extra_seo %}
{{ block.super }}
<meta property="article:published_time" content="{{ post.pub_time }}">
<meta property="og:description" content="{{ post.desc }}">
<meta property="og:image" content="http://{{ request.META.HTTP_HOST }}{{ post.thumb.url }}">
{% endblock extra_seo %}

{% block body %}
{% include "partials/post_header.html" %}
<div class="post_body">
    {% include "partials/thumbnail.html" with url=post.thumb.url nt=True %}
    {{ post.body|render_md }}
</div>
{% if form and post.comments.count != 0 %}
    <div id="comments" class="comment_container">
        {% for comment in post.comments.all %}
            {% if not comment.parent %}
                {% include "partials/comment.html" %}
                {% for comment in comment.child.all %}
                    {% include "partials/comment.html" %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
{% elif form and post.comments.count == 0 %}
    <div id="comments" class="comment_container">
        <h2 class="no_comment">{% trans "There is no comment yet. Wanna be the first?" %}</h2>
    </div>
{% endif %}
{% if form %}
    {% include "partials/comment_form.html" %}
{% endif %}
{% endblock body %}

{% block js %}
{{ block.super }}
{% if form %}
    <script src="{% static "comment.js" %}"></script>
{% endif %}
{% endblock js %}

templates/index.html
{% extends 'base.html' %}

{% load markdown_tags %}
{% load i18n %}

{% block title %}
{% if q %}
    #{{ q }} | 
{% endif %}
{{ block.super }}
{% endblock title %}

{% block extra_header %}
{% if q %}
    <h3>
        {% blocktrans with q=q %}Results for keyword "{{ q }}"{% endblocktrans %}
    </h3>
{% endif %}
{% endblock extra_header %}

{% block body %}
{% for post in post_list %}
    {% include "partials/post_header.html" %}
    <div class="post_body">
        {% include "partials/thumbnail.html" with url=post.get_absolute_url %}
        {{ post.desc|render_md }}
        <h4>
            <a href="{{ post.get_absolute_url }}">
                {% trans "Read More" %}
            </a>
        </h4>
    </div>
{% endfor %}
{% if page_obj.has_previous or page_obj.has_next %}
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
        {% endif %}
        {% if page_obj.has_next %}
            <a class="right" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
        {% endif %}
    </div>
{% endif %}
{% endblock body %}